version: '3.8'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: organization-api-docs
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/share/nginx/html/specs
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/specs/ipsreleasenofun.yml
    restart: unless-stopped

  dev-pg12:
    container_name: soa
    image: postgres:17
    environment:
      POSTGRES_DB: soa
      POSTGRES_USER: soa
      POSTGRES_PASSWORD: soasoa
    volumes:
      - dev-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ib -d ib"]
      interval: 5s
      timeout: 5s
      retries: 3



volumes:
  dev-db-volume: {}

