version: '3.8'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: organization-api-docs
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/share/nginx/html/specs
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/specs/ipsreleasenofun.yml
    restart: unless-stopped