server:
  port: 8081
  servlet:
    context-path: /organization-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soa
    username: soa
    password: soasoa
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.fergoeqs: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE