FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

COPY frontend /usr/share/nginx/html

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY certs-scripts/generate-certs.sh /generate-certs.sh
RUN chmod +x /generate-certs.sh

ENTRYPOINT ["/entrypoint.sh"]
